#!/usr/bin/env bash

declare -a FILELIST=()
FILELIST+=('etc/sddm.conf')
FILELIST+=('home/jasper/.config/eza/theme.yml')
FILELIST+=('home/jasper/.config/fastfetch/config.jsonc')
FILELIST+=('home/jasper/.config/fastfetch/the-ship-logo.png')
FILELIST+=('home/jasper/.config/fastfetch/the-ship-logo.txt')
FILELIST+=('home/jasper/.config/fish/config.fish')
FILELIST+=('home/jasper/.config/hypr/')
FILELIST+=('home/jasper/.config/kitty/kitty.conf')
FILELIST+=('home/jasper/.config/kitty/theme-fold.conf')
FILELIST+=('home/jasper/.config/logid/logid.cfg')
FILELIST+=('home/jasper/.config/mako/config')
FILELIST+=('home/jasper/.config/starship.toml')
FILELIST+=('home/jasper/.config/tofi/config')
FILELIST+=('home/jasper/.config/waybar/config.jsonc')
FILELIST+=('home/jasper/.config/waybar/style.css')
FILELIST+=('home/jasper/.config/yazi/keymap.toml')
FILELIST+=('home/jasper/.config/yazi/yazi.toml')
FILELIST+=('home/jasper/.gitconfig')
FILELIST+=('home/jasper/.mozilla/firefox/s8csmeui.default-release/chrome/userChrome.css')
FILELIST+=('home/jasper/pictures/wallpapers/foldward/')
FILELIST+=('usr/share/sddm/scripts/Xsetup')
FILELIST+=('usr/share/sddm/scripts/Xstop')
FILELIST+=('usr/share/sddm/themes/bg.png')
FILELIST+=('usr/share/sddm/themes/obscure/')