"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
   { on = "w", run = "arrow prev" },
   { on = "s", run = "arrow next" },
   { on = "a", run = "leave" },
   { on = "d", run = "enter" },
]

# w - 
# a - create file
# s - search fd (S - search ripgrep)
# d - trash files (D - delete)